### ISSUE TITLE
未来可能还需要改进的几个问题

### ISSUE THREAD

**Issue by macdao** [gdut-yy/Domain-Driven-Design-zh#8]
这份文档很大程度上方便了我的工作，非常感谢张逸扬！

我希望它可以更好，也在帮助改进。除此之外我还发现这样一些问题，想拿出来讨论一下：

1. 缺少一些格式。比如强调、小的章节标题、一些额外的说明
2. 表格没有翻译
3. 缺少reference的标注
4. 潜在的需要修正的文字

我认为这些都是需要改进的

有几个可能是问题：

1. 中文都是以“引用”的格式显示。因为引用毕竟有一些样式影响，如果有了格式，可能会出现冲突
2. 表格是图片
3. 一些图片没有翻译

**Comment by gdut-yy** [comment]
@macdao 感谢你的 PR，你上述的问题的确存在。并且部分修正起来可能需要不少的工作量。

本 Repo 是本人翻译系列的其中一个，我认为它有以下一些亮点：

- 比起纸质书，容易携带，提供中英双语，可更容易理解作者原意；
- 比起 PDF 版本，Web 版不用下载，更易于阅读；
- 比起 Wx 阅读等移动端阅读 App，不用登陆账号，可自由复制粘贴；

同时可能存在一些问题：

- 版权问题；
- 法律风险；

从技术角度而言，由于 vuepress 支持 vue 组件以及 HTML 嵌套，大部分样式问题都可以修正。

从我个人的角度：

- 平时设计架构时会翻翻重温一下作者的观点，不太关注一些样式细节；
- 加班多 + 比较懒 hhh

**Comment by macdao** [comment]
了解了。谢谢回复。

有可能的话，我会继续提供PR，改进部分问题。
